apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-secrets
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-key: {{ .Values.secret.jwtKey | quote }}
