apiVersion: v1
kind: Service
metadata:
  name: taskflow-api
  namespace: taskflow
spec:
  selector:
    app.kubernetes.io/name: taskflow-api
  ports:
    - name: http
      port: 8080
      targetPort: http
