apiVersion: v1
kind: Service
metadata:
  name: taskflow-mvc
  namespace: taskflow
spec:
  selector:
    app.kubernetes.io/name: taskflow-mvc
  ports:
    - name: http
      port: 8081
      targetPort: http
